#! /usr/bin/env python
# -*- coding: utf-8 -*-

# eLyXer configuration
# autogenerated from elyxer.config file on 2010-03-15

class GeneralConfig(object):
  "Configuration class from elyxer.config file"

  version = {
      'date':'2010-03-15', 'number':'0.1', 
      }

class JavaToPyConfig(object):
  "Configuration class from elyxer.config file"

  declarations = {
      '$andvalue':'$value && $value', 
      '$arithmeticexpression':'$value + $value', 
      '$assignment':'$variablename = $value;', '$block':'[$statement]*', 
      '$class':'$scope class $classname $inheritance { [$method]* }', 
      '$classlist':'[$classname]?[, $classname]*', '$classname':'$$', 
      '$condition':'$value|$logicalvalue', 
      '$conditional':'if ($condition) $block', 
      '$declaration':'$simpledeclaration|$declarationassignment', 
      '$declarationassignment':'$type $variablename = $value;', 
      '$file':'[$class]+', 
      '$inheritance':'[extends $classlist]? [implements $classlist]?', 
      '$logicalvalue':'$orvalue|$andvalue', 
      '$method':'$scope [$qualifier]* $type $methodname ( $paramsdeclaration ) { $block }', 
      '$methodcall':'$variablename[.$methodname($params)]+', 
      '$methodname':'$$', '$orvalue':'$value || $value', 
      '$paramdeclaration':'$type $variablename', 
      '$params':'[$value]?[,$value]+', 
      '$paramsdeclaration':'[$paramdeclaration]?[,$paramdeclaration]*', 
      '$qualifier':'static|final', '$scope':'public|private|protected', 
      '$simpledeclaration':'$type $variablename;', 
      '$statement':'$conditional|$declaration|$assignment|$methodcall', 
      '$type':'int|String|$classname', 
      '$value':'$variablename|$methodcall|$arithmeticexpression', 
      '$variablename':'$$', 
      }

  output = {
      '$class':'class $classname(object):\\n\\t[$method]*', 
      '$classname':'$classname', 
      '$conditional':'if $condition:\\n\\t$block', 
      '$method':'def $methodname:\\n\\t$block', 
      }

